const comments = [
  "I’m happy to see you working like that",
  "You’ve just about mastered that",
  "Fine!",
  "That’s the best you’ve ever done",
  "Wow!",
  "Keep working on it. You’re good",
  "Couldn’t have done it better myself",
  "Good work!",
  "Now that’s what I call a fine job",
  "You’re doing beautifully",
  "Superb!",
  "Keep it up",
  "You certainly did well",
  "Tremendous!",
  "You’re doing fine",
  "I’ve never seen anyone do it better",
  "Good for you!",
  "Good going!",
  "I like that",
  "I’m very proud of you",
  "I think you’ve got it now",
  "Good job!",
  "That’s really nice",
  "You’re right",
  "Clever!",
  "That makes me feel good",
  "That’s great!",
  "Way to go!",
  "Well, look at you go",
  "Wonderful!",
  "Super!",
  "Marvelous!",
  "You’ve got it made",
  "That’s right!",
  "You’re on the right track now",
  "That’s good!",
  "You are very good at that",
  "You’re doing a good job",
  "You’ve just about got it",
  "Great!",
  "Good for you!",
  "You’re getting better every year",
  "That’s the way!",
  "Nice going",
  "Sensational!",
  "That’s better",
  "Nothing can stop you now",
  "Excellent!",
  "Perfect!",
  "That’s the best ever",
  "Terrific!",
  "That’s better than ever",
  "Outstanding!",
  "You did very well!",
  "You’re really improving",
  "Right on!",
  "You’re on target now!",
  "I’m impressed with your progress!",
  "Incredible job!",
  "Awesome job!"
];

export default comments;